version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000"
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.vue-store-server.rule=Host(`vue-store-server.tahsin.us`)
      - traefik.http.routers.vue-store-server.entrypoints=websecure
      - traefik.http.services.vue-store-server.loadbalancer.server.port=80
      - traefik.http.routers.vue-store-server.tls=true
      - traefik.http.routers.vue-store-server.tls.certresolver=myresolver
    networks:
      - traefik

networks:
  traefik:
    external: true
